[display]
width      = 1280
height     = 480
fullscreen = false
fps        = 60

[vehicle]
profile    = toyota

[data]
; mode options: simulation / can / obd
mode       = simulation
can_channel  = can0
can_bustype  = socketcan
obd_port     = auto

[ui]
theme           = dark
; default_surface: 0=HUD  1=Infotainment  2=Rear
default_surface = 0
units           = mph

[gpio]
enabled  = false
pin_hud  = 17
pin_info = 27
pin_rear = 22
pin_theme = 23
